### ISSUE TITLE
Paper corresponding to the code

### ISSUE THREAD

**Issue by Onepersonformsaarmy** [sustainable-computing/Distribution-Grid-Identification#2]
Hello, I am going to use your code to calculate the IEEE123 power flow, and generate the network topology through the voltage of each node. I hope to quote your paper, but I can't find it. Can you share an address? Thanks a lot.

**Comment by Onepersonformsaarmy** [comment]
Also, where did you get this active power data?

**Comment by rajuwagle** [comment]
> Hello, I am going to use your code to calculate the IEEE123 power flow, and generate the network topology through the voltage of each node. I hope to quote your paper, but I can't find it. Can you share an address? Thanks a lot.



> Hello, I am going to use your code to calculate the IEEE123 power flow, and generate the network topology through the voltage of each node. I hope to quote your paper, but I can't find it. Can you share an address? Thanks a lot.

hello, Did you manage to simulate the program without any problem. I had a problem while running COM interface for OpenDSS

**Comment by Onepersonformsaarmy** [comment]
Yes, I successfully run the COM interface in matlab. However, when calculating the IEEE123 node power flow, the load of the node cannot be changed. I modified this.

**Comment by Onepersonformsaarmy** [comment]
> Hello, I am going to use your code to calculate the IEEE123 power flow, and generate the network topology through the voltage of each node. I hope to quote your paper, but I can't find it. Can you share an address? Thanks a lot.
> 
> 
> Hello, I am going to use your code to calculate the IEEE123 power flow, and generate the network topology through the voltage of each node. I hope to quote your paper, but I can't find it. Can you share an address? Thanks a lot.
> 
> hello, Did you manage to simulate the program without any problem. I had a problem while running COM interface for OpenDSS

Yes, I successfully run the COM interface in matlab. However, when calculating the IEEE123 node power flow, the load of the node cannot be changed. I modified this.

**Comment by ardakanian** [comment]
Please cite this paper: "O. Ardakanian et al., "On Identification of Distribution Grids," in IEEE Transactions on Control of Network Systems, vol. 6, no. 3, pp. 950-960, Sept. 2019, doi: 10.1109/TCNS.2019.2891002."

https://ieeexplore.ieee.org/document/8601410
